version: '3.8' 


networks:
  node-db:
    driver: bridge

services: 
  node: 
    container_name: "Diary-app"
    restart: always
    build: 
      context: .
    networks:
      - "node-db"
    ports: 
      - "8080:8080" 
    expose: 
      - "8080"
    depends_on: 
    - mysql 
    
  db: 
    container_name: "Diary-db"
    restart: always
    hostname: "Diary-db"
    ports: 
    - "3307:3306" 
    image: mariadb:10.6.7-focal
    # image: mysql/mysql-server:5.7.28
    # platform: linux/x86_64
    # command: --default_authentication_plugin=mysql_native_password
    networks:
      - "node-db"
    volumes:
      - "./database/seeders/init.sql:/data/application/init.sql"
    environment: 
      - MYSQL_ROOT_PASSWORD=testpwd
      - MYSQL_DATABASE=diary
      - MYSQL_USER=me